Repository hpsim/OBR, pull requests merged in 2023-06, with the labels that each got.

#85 List operations
  docs/source/commandLine/CLI.md
  docs/source/commandLine/operations.md
  docs/source/commandLine/run.md
  src/obr/cli.py
  src/obr/signac_wrapper/operations.py
Labels: documentation, enhancement, ready-to-review

#89 Feature/coverage
  .github/workflows/tests.yml
  README.md
  pyproject.toml
Labels: ready-to-review, ready-to-merge

#91 Refactor caseOrigins
  src/CaseOrigins.py
  src/obr/core/caseOrigins.py
  src/obr/signac_wrapper/operations.py
Labels: ready-to-review

#93 Add a member to return all time folder
  src/obr/OpenFOAM/case.py
  tests/test_OpenFOAMCase.py
Labels: ready-to-merge

#95 Fix/generate
  src/obr/cli.py
  src/obr/create_tree.py
  tests/test_md5sum.py
  tests/test_queries.py
Labels: ready-to-review

#90 refactor runSolver operations
  .github/workflows/tests.yml
  src/obr/cli.py
  src/obr/signac_wrapper/operations.py
  tests/cavity.yaml
Labels: ready-to-merge

#97 Minor Quality-of-Life changes
  docs/source/index.md
  src/obr/cli.py
  src/obr/core/core.py
  src/obr/core/parse_yaml.py
  src/obr/core/queries.py
  src/obr/create_tree.py
  src/obr/signac_wrapper/operations.py
Labels: enhancement, ready-to-review

#98 AttributeError: 'BufferedJSONAttrList' object has no attribute 'get'
  src/obr/signac_wrapper/labels.py
Labels: ready-to-review, stability

#99 change logging format filename
  src/obr/cli.py
Labels: bug

#104 Fix Typos
  .github/workflows/typo_check.yml
  README.md
  _typos.toml
  docs/source/index.md
  src/obr/OpenFOAM/solver.py
  src/obr/core/caseOrigins.py
  src/obr/core/core.py
  src/obr/core/queries.py
  src/obr/create_tree.py
  src/obr/signac_wrapper/labels.py
  src/obr/signac_wrapper/operations.py
  tests/test_create_tree.py
  tests/test_md5sum.py
  tests/test_yaml_parser.py
Labels: ready-to-review

#103 add to_records and to_dataframe from yaml examples
  pyproject.toml
  src/obr/core/queries.py
  tests/test_queries.py
Labels: ready-to-review
